version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "CI"
    labels: ["dependencies"]

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "Зависимости"
    labels: ["dependencies"]
    open-pull-requests-limit: 5
